### ISSUE TITLE
Superflow billing (decision)

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/data-science#25]
@usamabilal we need to make a decision of superflow. Our 10 day 'Free Agency trial' is ending in 4 days. and we will revert to free tier which has only one project (one site we can work on). This is problematic as we will be utilize more than 1 project definitely. 

So far my impressions are A+. Great customer service, great UI and has already save us hours of man hours + increase rate of iteration. 

See [table](https://github.com/Drexel-UHC/data-science/files/12752900/Superflow.cost.analysis.tabl.xlsx) below that summarizes expected billing and minimum man-hours of ROI annually. Lmk if you have any questions or want to zoom real quick. 

 <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ranli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ranli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Plan | Projects | Users | Cost Y1 | Manhours Saved Y1 | Cost Y2 | Manhours Saved Y2
-- | -- | -- | -- | -- | -- | --
Freelancer | 3 | 5 | 174 | 4 | 261 | 5
Agency | Unlimited | 7 | 354 | 7 | 531 | 11

</body>

</html>

- Year 1 is 50% academic discount
- Year 2+ is 25% academic discount
- Manhours saved assumes 100k salary (~$45 per hour)

## Recomendation

- **A Agency plan.**
   - we want to have unlimited projcects. I think 3 is too limiting. 
   -  As an individual (Ran) it will save at least 7 hours over a year. But including collab across roles/teams... this we save a  lot than 7 hours total...

**Comment by usamabilal** [comment]
I'm 100% for this. Just a couple questions:
- this still allows unlimited people sgining in to comment?
- what's the Users column?

**Comment by ran-codes** [comment]
No. Superbase doesn't work like markerio. **There is a limited number of reporters/admin per project; this is reflected in the users column**. For example for salurbal portal if we have the `agency` plan only 7 people can be involved at once. I think this is fine as mostly we have internal people using superbase? thoughts?


As to why the billing is different compared to markerio. Is that markerio is a screenshot based system not a actual DOM manipulation/annotation system. so the tech is more expensive. see convo below.

![image](https://github.com/Drexel-UHC/data-science/assets/45013044/4eb65059-6d5f-4674-90e2-7f5d9f05d587)

**Comment by usamabilal** [comment]
Ok! Lets do an agency one then. Lmk where to go to pay (may need a temp password).
To confirm:
- we can do unlimited projects
- EACH project can only have 7 reviewers
Who else at the UHC do you think would benefit from this? You'd be "admin" of this product, but we should offer to others. Rebecca? Future Andrea?

**Comment by ran-codes** [comment]
## COnfirmations

- we can do unlimited projects **YES**
- EACH project can only have 7 reviewers **YES**

## Users

Rebecca, future Andrea.. and key stakeholders/clients. E.g. if we make a scrolly for BCHC or etc their people can iterate using that. 

## Billing

I will try get you the links/passwords tomorrow.

**Comment by ran-codes** [comment]
## Billing Instructions

1. @usamabilal you have been invited to be a superflow admin (check your Gmail). 
2. Accept admin invitation
3. login using their your own account: https://app.usesuperflow.com/dashboard
4. Click Billing on sidebar
5. Scroll down and click `Upgrade` to an Agency plan (see snip 1)
6. Checkout using the PROMO code `NONPROFITSF50` for 50% off 

slack me if questions or just ask rakesh if you want (he's very good). 

### Snip 1
![image](https://github.com/Drexel-UHC/data-science/assets/45013044/ef205c9c-de96-4621-b27c-efa4ab6e5f2b)

**Comment by usamabilal** [comment]
I don't have anything on my gmail...
usamabilal@gmail.com

**Comment by ran-codes** [comment]
## Can you try clicking billing?

(you are an admin on the dashboard). Does it show that for you when you click user?
 
![image](https://github.com/Drexel-UHC/data-science/assets/45013044/50f1f12c-6562-45e2-909c-b3576b07b630)

**Comment by usamabilal** [comment]
Done!
